[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# SPA routing redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for production
[[redirects]]
  from = "/api/*"
  to = "https://api.omniverse.ai/api/:splat"
  status = 200
  force = false

# Fallback API proxy
[[redirects]]
  from = "/fallback-api/*"
  to = "https://backend.omnidim.io/api/:splat"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://backend.omnidim.io https://www.youtube.com https://youtube.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://backend.omnidim.io https://api.omniverse.ai; frame-src 'self' https://www.youtube.com https://youtube.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these should be set in Netlify dashboard)
# VITE_API_URL_PRODUCTION = "https://api.omniverse.ai"
# VITE_API_URL = "https://backend.omnidim.io"
# VITE_VOICE_AGENT_API_KEY = "hW9MprUtUHNXwakl-aXp2Tqy-Dfz0Q3IhMEx2ntqo5E"
# VITE_OMNIVERSE_SECRET_KEY = "201ff4fd19c1ffd37b272cc1eacb874a"
# VITE_APP_ENVIRONMENT = "production"
