[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Performance optimizations
  NODE_OPTIONS = "--max-old-space-size=4096"
  GENERATE_SOURCEMAP = "false"
  INLINE_RUNTIME_CHUNK = "false"

# Build processing optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# SPA routing redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for production
[[redirects]]
  from = "/api/*"
  to = "https://api.omniverse.ai/api/:splat"
  status = 200
  force = false

# Fallback API proxy
[[redirects]]
  from = "/fallback-api/*"
  to = "https://backend.omnidim.io/api/:splat"
  status = 200
  force = false

# Security headers with enhanced CDN support
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://backend.omnidim.io https://www.youtube.com https://youtube.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https: https://cdn.jsdelivr.net https://iaddy.netlify.app; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://backend.omnidim.io https://api.omniverse.ai https://iaddy.netlify.app; frame-src 'self' https://www.youtube.com https://youtube.com;"

# Cache static assets with versioned filenames
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache images with optimization
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    X-Content-Type-Options = "nosniff"

# Cache JavaScript and CSS
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache manifest and service worker with shorter cache
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"

# Cache HTML with short cache for updates
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    X-Content-Type-Options = "nosniff"

# Environment variables (these should be set in Netlify dashboard)
# VITE_API_URL_PRODUCTION = "https://api.omniverse.ai"
# VITE_API_URL = "https://backend.omnidim.io"
# VITE_VOICE_AGENT_API_KEY = "hW9MprUtUHNXwakl-aXp2Tqy-Dfz0Q3IhMEx2ntqo5E"
# VITE_OMNIVERSE_SECRET_KEY = "201ff4fd19c1ffd37b272cc1eacb874a"
# VITE_APP_ENVIRONMENT = "production"
